# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4264aef4f043efb2f3cddc2f933e24b327883b6edbeda0823c648969c5c8b2ea0bb200d4448d47668caef4e6320d2e5b352eee8e8849577f7d0d2c22661c3bf4

test:
  secret_key_base: ea595674621add4484057b29f4699b772b9bad76096d5aebc1ca20e6f01ed3bed84eac673f164bfed7c48124c72da16fafb658160b1e2742dcd5e3530b86f548

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
