# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4db73c67125eff6f7a6ee5bc048a9e0eed699fb881f67288b4ee14b89e77b8a7ad0b7b2d0b564285de436ed4ee8d8382d709ac3a40e91fe11bb9fdf9c81625f9

test:
  secret_key_base: d238be568ee0de75264253e1559c369890ce1681c44fdb81a9871a8ef15fb1b77869189a90830d7f660ef2985fccc1aac1ca6a063777f0ddf17e1ba7ea22352c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
